openapi: 3.0.0
info:
  title: FNB API
  description: API for managing products with Swagger
  version: 1.0.0
servers:
  - url: http://localhost:3000

tags:
  - name: Product
    description: Everything about your Products
  - name: Category
    description: Product Category

paths:
  /api/getProducts:
    get:
      tags:
        - Product
      summary: Get all products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/addProduct:
    post:
      tags:
        - Product
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: The created product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/deleteProduct/{id}:
    delete:
      tags:
        - Product
      summary: Delete a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to delete
      responses:
        "200":
          description: Product deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/updateProduct/{id}:
    put:
      tags:
        - Product
      summary: Update a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/getCategories:
    get:
      summary: Lấy danh sách tất cả các danh mục
      tags:
        - Category
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: integer
          description: ID của sản phẩm
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category_id:
          type: integer
        img:
          type: string
      example:
        product_id: 1
        name: Example Product
        description: This is an example product
        price: 100.0
        category_id: 1
        img: https://example.com/product.jpg

    ProductInput:
      type: object
      required:
        - name
        - description
        - price
        - category_id
        - img
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category_id:
          type: integer
        img:
          type: string
      example:
        name: Example Product
        description: This is an example product
        price: 100.0
        category_id: 1
        img: https://example.com/product.jpg

    Category:
      type: object
      properties:
        category_id:
          type: integer
          description: ID của danh mục
        name:
          type: string
          description: Tên của danh mục
      example:
        category_id: 1
        name: Example Category

    Message:
      type: object
      properties:
        message:
          type: string
      example:
        message: Operation successful

    Error:
      type: object
      properties:
        error:
          type: string
      example:
        error: Operation error